# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setAlignment(QtCore.Qt.AlignCenter)  # Corrigido
        self.label_output.setObjectName("label_output")
        self.verticalLayout.addWidget(self.label_output)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.slider_v_min = QtWidgets.QSlider(self.centralwidget)
        self.slider_v_min.setMaximum(255)
        self.slider_v_min.setOrientation(QtCore.Qt.Horizontal)  # Corrigido
        self.slider_v_min.setObjectName("slider_v_min")
        self.gridLayout.addWidget(self.slider_v_min, 4, 2, 1, 1)
        self.slider_s_max = QtWidgets.QSlider(self.centralwidget)
        self.slider_s_max.setMaximum(255)
        self.slider_s_max.setProperty("value", 255)
        self.slider_s_max.setOrientation(QtCore.Qt.Horizontal)  # Corrigido
        self.slider_s_max.setObjectName("slider_s_max")
        self.gridLayout.addWidget(self.slider_s_max, 3, 2, 1, 1)
        self.slider_v_max = QtWidgets.QSlider(self.centralwidget)
        self.slider_v_max.setMaximum(255)
        self.slider_v_max.setProperty("value", 255)
        self.slider_v_max.setOrientation(QtCore.Qt.Horizontal)  # Corrigido
        self.slider_v_max.setObjectName("slider_v_max")
        self.gridLayout.addWidget(self.slider_v_max, 6, 2, 1, 1)
        self.slider_h_max = QtWidgets.QSlider(self.centralwidget)
        self.slider_h_max.setMaximum(179)
        self.slider_h_max.setProperty("value", 179)
        self.slider_h_max.setOrientation(QtCore.Qt.Horizontal)  # Corrigido
        self.slider_h_max.setObjectName("slider_h_max")
        self.gridLayout.addWidget(self.slider_h_max, 1, 2, 1, 1)
        self.slider_s_min = QtWidgets.QSlider(self.centralwidget)
        self.slider_s_min.setMaximum(255)
        self.slider_s_min.setOrientation(QtCore.Qt.Horizontal)  # Corrigido
        self.slider_s_min.setObjectName("slider_s_min")
        self.gridLayout.addWidget(self.slider_s_min, 2, 2, 1, 1)
        self.slider_h_min = QtWidgets.QSlider(self.centralwidget)
        self.slider_h_min.setMaximum(179)
        self.slider_h_min.setOrientation(QtCore.Qt.Horizontal)  # Corrigido
        self.slider_h_min.setObjectName("slider_h_min")
        self.gridLayout.addWidget(self.slider_h_min, 0, 2, 1, 1)
        self.label_v_max = QtWidgets.QLabel(self.centralwidget)
        self.label_v_max.setObjectName("label_v_max")
        self.gridLayout.addWidget(self.label_v_max, 6, 0, 1, 1)
        self.label_s_min = QtWidgets.QLabel(self.centralwidget)
        self.label_s_min.setObjectName("label_s_min")
        self.gridLayout.addWidget(self.label_s_min, 2, 0, 1, 1)
        self.label_s_max = QtWidgets.QLabel(self.centralwidget)
        self.label_s_max.setObjectName("label_s_max")
        self.gridLayout.addWidget(self.label_s_max, 3, 0, 1, 1)
        self.label_v_min = QtWidgets.QLabel(self.centralwidget)
        self.label_v_min.setObjectName("label_v_min")
        self.gridLayout.addWidget(self.label_v_min, 4, 0, 1, 1)
        self.label_h_min = QtWidgets.QLabel(self.centralwidget)
        self.label_h_min.setObjectName("label_h_min")
        self.gridLayout.addWidget(self.label_h_min, 0, 0, 1, 1)
        self.label_h_max = QtWidgets.QLabel(self.centralwidget)
        self.label_h_max.setObjectName("label_h_max")
        self.gridLayout.addWidget(self.label_h_max, 1, 0, 1, 1)
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)  # Renomeado
        self.btn_reset.setObjectName("btn_reset")
        self.gridLayout.addWidget(self.btn_reset, 7, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Controles HSV"))
        self.label_output.setText(_translate("MainWindow", "[Imagem Aqui]"))
        self.label_v_max.setText(_translate("MainWindow", "V Max: 255"))
        self.label_s_min.setText(_translate("MainWindow", "S Min: 0"))
        self.label_s_max.setText(_translate("MainWindow", "S Max: 255"))
        self.label_v_min.setText(_translate("MainWindow", "V Min: 0"))
        self.label_h_min.setText(_translate("MainWindow", "H Min: 0"))
        self.label_h_max.setText(_translate("MainWindow", "H Max: 179"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))  # Atualizado