# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_original = QtWidgets.QLabel(self.centralwidget)
        self.label_original.setAlignment(QtCore.Qt.Qt.AlignCenter)
        self.label_original.setObjectName("label_original")
        self.verticalLayout.addWidget(self.label_original)
        self.label_filtered = QtWidgets.QLabel(self.centralwidget)
        self.label_filtered.setAlignment(QtCore.Qt.Qt.AlignCenter)
        self.label_filtered.setObjectName("label_filtered")
        self.verticalLayout.addWidget(self.label_filtered)
        self.btn_calibrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calibrar.setObjectName("btn_calibrar")
        self.verticalLayout.addWidget(self.btn_calibrar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_original.setText(_translate("MainWindow", "[Imagem Original]"))
        self.label_filtered.setText(_translate("MainWindow", "[Imagem Com Filtro]"))
        self.btn_calibrar.setText(_translate("MainWindow", "Abrir filtro HSV"))
